version: '2'

services:
  cache:
    image: memcached:1.4-alpine

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'

  bionexo_ubs_api:
    extends:
      file: common.yml
      service: bionexo_ubs_api
    tty: true
    stdin_open: true

volumes:
  db:
    external: false