default: &defaults
  adapter: postgresql
  host:     <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *defaults
  adapter: postgresql
  database: bionexo_ubs_development

test:
  <<: *defaults
  adapter: postgresql
  database: bionexo_ubs_test

production:
  <<: *defaults
  adapter: postgresql
  database: bionexo_ubs_production

  staging:
  <<: *defaults
  adapter: postgresql
  database: bionexo_ubs_staging
  